// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOV4hbdjdbhHwabMJORaDYZZBjchRfuY',
    appId: '1:948308348956:web:be2157e5dded41d56e4fd9',
    messagingSenderId: '948308348956',
    projectId: 'chat-app-33c83',
    authDomain: 'chat-app-33c83.firebaseapp.com',
    storageBucket: 'chat-app-33c83.appspot.com',
    measurementId: 'G-R4K9MKM73K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-TdV8B5MP6bOsbiDaBKwMIQXSsFSBDbM',
    appId: '1:948308348956:android:f09983e6885638c56e4fd9',
    messagingSenderId: '948308348956',
    projectId: 'chat-app-33c83',
    storageBucket: 'chat-app-33c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ztoZ7DySvmrlZKlMrNQBHUVJpJdOItw',
    appId: '1:948308348956:ios:e543f9f199bd99fb6e4fd9',
    messagingSenderId: '948308348956',
    projectId: 'chat-app-33c83',
    storageBucket: 'chat-app-33c83.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
